### ISSUE TITLE
Script dies without giving a heartbeat

### ISSUE THREAD

**Issue by amingilani** [arjunmehta/heartbeats#9] opened 2016-11-18 12:07 UTC
Originally posted on [SO](https://stackoverflow.com/questions/40675789/why-does-my-heartbeat-process-die-as-soon-as-it-starts)

I have a simple heartbeat process that should run forever and continue beating, but it dies as soon I start it.

```bash
$ node heartbeat.js
Starting heartbeats
$
```
My heartbeat script is quite straightforward.

```javascript
var heartbeats = require('heartbeats');

// tell me that the script is starting
console.log('Starting heartbeats');

// create a heart that beats every second
var heart = heartbeats.createHeart(1000);

// every heartbeat, tell me the beat number
heart.createEvent(1, function(heartbeat, last){
  console.log('beat number ' + heart.age);
});
```

However adding process.stdin.resume(); at the end keeps it running forever:

```bash
$ node heartbeat.js
Starting heartbeats
beat number 1
beat number 2
beat number 3
...
```
Why does it do this?

**Comment by arjunmehta** [comment] 2016-11-18 20:57
Hi there @amingilani,

Heartbeats isn't meant to keep your app alive. I should clarify that in the readme. But your question got me thinking about expected behavior. I think it makes sense that you would expect the app to be kept alive when you create events.

Because you are using `process.stdin.resume();` you are able to keep your app alive for heartbeats to do its thing.

For now, instead at the end of your code you can use `heart.interval.ref()`.

This will keep your app alive as long as the event exists.

**Comment by arjunmehta** [comment] 2016-11-18 21:47
@amingilani In response to your question, I've just pushed a fix, and a new version of Heartbeats ->  `npm install --save heartbeats@4.0.0`

This new version should behave as expected. Please continue to report any unexpected bugs or behavior you may encounter!

Thank you!

**Closed by arjunmehta** 2016-11-18 21:47 UTC

**Comment by amingilani** [comment] 2016-11-19 20:26
Shukriya Arjun! This is awesome!
